scripts/download-and-extract-fixtures.sh

This PR makes the download script always download the latest `zkevm@vX.X.X` tag from `execution-spec-tests` repo, compared with a fixed tag. If the user wants to download a particular version, they can provide it as an argument.
Example run:
```
$ ./scripts/download-and-extract-fixtures.sh      
🔎  Finding the latest release tag with prefix 'zkevm@'...
ℹ️  Using latest found tag: zkevm@v0.0.2
🔎  Getting release info for zkevm@v0.0.2 …
⬇️  Downloading fixtures_zkevm.tar.gz …
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 4388k  100 4388k    0     0  3897k      0  0:00:01  0:00:01 --:--:-- 22.1M
📂  Extracting to ./zkevm-fixtures/
🗑️ …
```

scripts/fixtures: avoid fixed tags by downloading latest release by default

---

Cargo.lock
Cargo.toml
crates/benchmark-runner/Cargo.toml
crates/benchmark-runner/src/lib.rs
crates/zkevm-risc0/host/Cargo.toml
crates/zkevm-risc0/host/src/main.rs
crates/zkevm-succinct/host/Cargo.toml
crates/zkevm-succinct/host/src/main.rs
crates/zkevm-zkm/host/Cargo.toml
crates/zkevm-zkm/host/src/main.rs

This PR creates a `benchmark-runner` component responsible for parsing the corpus of tests and allows them to be run in parallel.
My motivation is that we now have multiple tests, and zkVM runs them serially (and takes a while). This means that running the whole corpus takes a lot of time.
Running each is independent, so this can give 8x to 16x speedup in running the whole corpus, depending on how many cores you have in your machine. More probably, running the entire corpus reduces to the slowest test in the suite.

Create benchmark runner and allow parallel execution

---

crates/benchmark-runner/src/lib.rs
crates/ere-hosts/src/main.rs
crates/metrics/src/lib.rs

Main change is that we can specify execute or proving

feat: Refine benchmark runner API

---

Cargo.lock
Cargo.toml
crates/benchmark-runner/src/lib.rs
crates/metrics/README.md
crates/metrics/src/lib.rs
ere-guests/risc0/guest/Cargo.toml

This PR:
- Updates `ere` and pins to a specific commit (latest now), so we don't have a non-well defined dependency target in case of breaking changes happening.
- Fixes risc0 guest program to allow for `getrandom` feature.
The last bullet was discovered when I tried to run mainnet blocks with risc0 and got this panic:
```
thread 'main' panicked at /home/ignacio/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/risc0-zkvm-platform-2.0.2/src/getrandom.rs:63:5:
WARNING: `getrandom()` called from guest.
=========================================
This panic was generated from the guest program calling `getrandom()`.
Using randomness in the zkVM requires careful attention to your
application’s security requirements. Therefore, the default behavior is
for the zkVM to generate this panic …
```

risc0 getrandom and ere update

---

crates/benchmark-runner/src/lib.rs
crates/ere-hosts/src/main.rs

I was running benchmarks for two zkVMs for mainnet blocks and I realized the way things were wasn't ideal.
The witness generation call was done on each benchmark zkVM run, which for mainnet blocks means each will pull different blocks since we pul the last N blocks.
This PR changes the logic to generate the witness once, and use the same corpus on each zkVM. This also avoid generating witnesses repeatedly which would speed up benchmarks a bit too. And also, is a small step in the direction of untangling witness generation from benchmark runs (e.g. new benchmark running is not async again).

Generate witness once before running benchmarks

---

.cargo/config.toml
Cargo.lock
Cargo.toml
crates/ere-hosts/Cargo.toml
crates/ere-hosts/src/main.rs
ere-guests/zisk/Cargo.toml
ere-guests/zisk/src/main.rs
precompile-patches/zisk.toml

- Order cargo alias alphabetically so it is easier to track.
- Add `ere-guests/zisk`, but not sure if it's has the necessary output for the benchmark to collect.
- Add `precompile-patches/zisk.toml`, but in org [0xPolygonHermez](https://github.com/0xPolygonHermez) there is only `tiny-keccak` patched repo, and an outdated patched [reth](https://github.com/0xPolygonHermez/zisk-patch-reth), not sure we should do the rest patches for them (e.g. `k256`). The supported precompiled could be found [here](https://0xpolygonhermez.github.io/zisk/getting_started/precompiles.html#available-precompiles-in-zisk).
- Add `zkVM::Zisk` in `ere_hosts`.
Todo:

Add `ere-guests/zisk`

---

.gitignore
crates/witness-generator/src/rpc.rs

This PR renames the generated output to avoid `mainnet` naming since the RPC generator can point to any network. 
Use the same name used as in L183.

witness-generator: RPC output renaming

---

crates/ere-hosts/src/main.rs

This PR fixes an existing compilation error if more than one zkEVM is enabled via features. This wasn't detected before since our current CI only does `cargo check` by allowing only one zkEVM, thus transferring ownership in the problematic variable was fine.

Fix compilation error when more than zkEVM is enabled

---

crates/witness-generator/src/rpc.rs

This PR resolves a TODO now that I could ask the devops team to enable the RPC that wasn't whitelisted.

witness-generator/rpc: use block hash to pull execution witness

---

crates/benchmark-runner/src/lib.rs
crates/ere-hosts/src/main.rs
crates/metrics/Cargo.toml
crates/metrics/README.md
crates/metrics/src/lib.rs

This PR does the following changes:
- Automatically detects CPU, RAM, and GPUs in the host machine and saves it in a `hardware.json` file at the root of `zkevm-metrics` output folder.
- Adds an extra field in each benchmark run output file named `gas_used` with the amount of gas used in the block. This is useful for later analytics (e.g., having a proving time of 1min in a 10M block is not the same as a 30M block, especially for mainnet block benchmark runs). Also, I'm interested in presenting "proving opcode X has X gas/s proving throughput" which can in trying to make sense of potential repricings.
- Avoid using a separate `crashed` folder for crashed runs. Every run now will have the expected output json file, and will signal `success` or `crashed`. (More about this in example outputs …

Include host hardware spec, block used gas, proof size and have more uniform crash handling in outputs

---

.github/workflows/rust_checks.yml

This PR makes some optimizations in the CI pipeline to avoid duplicated tasks and optimize the cache usage, considering we rely heavily on feature flags.
Usual previous theoretically warm runs [take ~3.5m](https://github.com/eth-act/zkevm-benchmark-workload/actions/runs/15932909249), and [now run in 42s](https://github.com/eth-act/zkevm-benchmark-workload/actions/runs/15937628922?pr=90).

ci: optimize checks

---

crates/benchmark-runner/src/lib.rs
crates/ere-hosts/readme.md
crates/ere-hosts/src/main.rs

Yesterday, the prover we're using for running the benchmark suite crashed because of OOM. If we re-run the suite, it will start from scratch. 
This PR changes the behavior of `ere-hosts` in the following way:
- By default, if it detects that in the output folder the to-be-run case exists, it skips it and prints a message in stdout. (e.g. `Skipping tests/zkevm/test_worst_stateful_opcodes.py::test_worst_storage_access_cold[fork_Prague-blockchain_test-absent_slots_False-SSTORE same value]-2 (already exists)`)
- The user can provide a `--force-rerun` flag to override this default behavior.
I'm not sure which default behavior was the best. I suspect that if the user decides to keep an existing `zkevm-metrics` folder and rerun it, it is probably for a retry, since the most natural thing for a …

benchmark-runner: add flag to handle reruns & add a flag for output folder

---

Cargo.toml
crates/benchmark-runner/Cargo.toml
crates/benchmark-runner/src/lib.rs
crates/ere-hosts/Cargo.toml
crates/ere-hosts/src/main.rs
crates/witness-generator/Cargo.toml
crates/witness-generator/src/eest_generator.rs
crates/witness-generator/src/main.rs

Fixes #95 
Example:
```
$ cargo run --release -p witness-generator tests --include Prague --include cold
Compiling witness-generator v0.1.0 (/home/ignacio/code/zkevm-benchmark-workload/crates/witness-generator)
Finished `release` profile [optimized] target(s) in 5.83s
Running `target/release/witness-generator tests --include Prague --include cold`
2025-07-01T14:36:38.232563Z  INFO witness_generator: Generating fixtures in folder: "zkevm-fixtures-input"
2025-07-01T14:36:40.964797Z  INFO witness_generator: Generating fixtures...
2025-07-01T14:36:41.071549Z ERROR witness_generator::eest_generator: Failed to load test case from ./zkevm-fixtures/fixtures/blockchain_tests/prague/eip2537_bls_12_381_precompiles/bls12_precompiles_before_fork/precompile_before_fork.json: an error occurred …
```

chore: use tracing for logging

---

.github/workflows/docker-build.yml

[Fix the CI building the Docker image](https://github.com/eth-act/zkevm-benchmark-workload/actions/runs/16129848928/job/45514989069). We didn't catch this because it only runs in `master`.

ci: fix docker building

---

Cargo.lock
Cargo.toml
crates/ere-hosts/src/main.rs
ere-guests/Cargo.toml
ere-guests/empty-program/sp1/Cargo.toml
ere-guests/rlp-encoding-length/sp1/Cargo.toml
ere-guests/rlp-encoding-length/sp1/src/main.rs
ere-guests/stateless-validator/sp1/Cargo.toml

This PR updates to a new `ere` version which allows to distinguish between:
- Workspace directory: which directory gets mounted at compilation time.
- Guest program directory: a _relative_ path within the workspace to be compiled.
The main benefits are:
- We can switch again guest program types for zkVMs to use workspace dependencies, which reduces the burden of matching dependency versions.
- Guest programs can now use the `guest-libs` as a dependency, which will help reduce repetition in all guest program types.
As a first example of the latter, the `BincodeBlock` type that we had to duplicate before is now shared between `ere-hosts` (which is the "sender" of the stdin) and the guest program (which is the receiver).

guest-programs: use new workspace mounting from ere

---

ere-guests/Cargo.lock
ere-guests/Cargo.toml

While working on a new version of https://github.com/eth-act/zkevm-benchmark-workload/pull/123, I encountered a weird issue that I initially thought was related to that PR change, but it wasn't.
In the last Reth fork update, we only changed the main workspace `Cargo.toml` reference, but not the `ere-guests` one, as we should.
A priori should be an easy ref change, but looks like the last Reth fork has a problem for guest programs, see:
```
2025-07-28T19:21:43.450223Z  INFO benchmark_runner: Running rpc_block_23019315
stderr: 
stderr: thread '<unnamed>' panicked at stateless-validator/sp1/src/main.rs:28:78:
stderr: called `Result::unwrap()` on an `Err` value: StatelessExecutionFailed("internal EVM error occurred when executing transaction …
```

ere-guests: use same reth fork as main workspace

---

.github/workflows/integration-tests.yml
crates/witness-generator-cli/Dockerfile

Fixes `witness-generation-cli` CI [failure](https://github.com/eth-act/zkevm-benchmark-workload/actions/runs/16680811518/job/47218771788) that only runs in `master`.

ci: bump rust version for witness-generator-cli image generation

---

precompile-patches/sp1.toml

With the new patches:
```
$ cargo prove build
cargo:warning=rustc +succinct --version: "rustc 1.88.0-dev\n"
[sp1]     Compiling crypto-bigint v0.5.5 (https://github.com/sp1-patches/RustCrypto-bigint?tag=patch-0.5.5-sp1-4.0.0#d4210297)
[sp1]     Compiling serde_with v3.14.0
[sp1]     Compiling bitvec v1.0.1
...
```
So all current PR ones are used.
The `sha2` was removed since it generated a warning from not being use:
```
cargo:warning=rustc +succinct --version: "rustc 1.88.0-dev\n"
[sp1]  warning: Patch `sha2 v0.10.8 (https://github.com/sp1-patches/RustCrypto-hashes?tag=patch-sha2-0.10.8-sp1-4.0.0#1f224388)` was not used in the crate graph.
```

precompile-patches: update for sp1

---

.github/workflows/integration-tests.yml
Cargo.lock
Cargo.toml

This PR:
- Use `ere` images so we avoid building base and SDK docker images which take a lot of time and generate GH rate limiting problems.
- I switched to using GH runners instead of devops. Now that the pipeline is less heavy it's better, since devops needed also an extra step to instal the C toolchain which takes time. Plus, sometimes it took 2m just to start the workflow compared to GH runners which start immediately.
- Refactor the guest program runs so we avoid duplication

ci: use ere images

---

.github/workflows/integration-tests.yml
ere-guests/Cargo.toml
ere-guests/empty-program/zisk/Cargo.toml
ere-guests/empty-program/zisk/src/main.rs

Add Zisk to the integration tests CI, only for the `empty-program` since `stateless-validator` is blocked by #142

CI: add Zisk to integration tests

---

.github/workflows/integration-tests.yml
Cargo.lock
Cargo.toml
ere-guests/Cargo.lock
ere-guests/empty-program/risc0/Cargo.toml
ere-guests/stateless-validator/risc0/Cargo.toml

- Upgrade `ere` to rev `5556109`
- Upgrade `risc0` guest to `3.0.1`
(now on single 5090 it takes ~12mins to prove a 45M block, no more first proving slowdown issue)

Upgrade `ere` to rev `5556109` and upgrade `risc0` guest to `3.0.1`

---

precompile-patches/sp1.toml

Recently, I [added](https://github.com/eth-act/zkevm-benchmark-workload/pull/153) a CI workflow which fails if some existing patch is claimed not to be applied, which probably means the patch is outdated compared to waht the `stateless-validator` dependency graph is using.
That's okay, but we still once in a while have to double check if any patch is missing since that's not detectable via CI of course.
This PR contains some changes for SP1:
- Adds some missing patches that are used indeed (not quite useful, but still apply so I think is better to stick to that rule).
- I keep the same ordering and naming as the [SP1 table docs](https://docs.succinct.xyz/docs/sp1/optimizing-programs/precompiles#patched-crates). This reduces the risk of manual checking, since different ordering or …

xtask: update sp1 patches

---

.github/workflows/integration-tests.yml
Cargo.lock
Cargo.toml

Update ere to v0.0.12. In particular, because it has a temporary workaround to allow using ZisK without patching ere's dep in this repo (https://github.com/eth-act/ere/pull/137).
To use ZisK remember to export:
- `CUDA_ARCH=sm_{xx}` to your corresponding GPU arch.
- For 4090/L40s you will need also `ZISK_UNLOCK_MAPPED_MEMORY=1`

chore: update ere to v0.0.12

---

.github/workflows/integration-tests.yml
.github/workflows/rust-checks.yml
Cargo.lock
Cargo.toml
ere-guests/Cargo.toml

After our latest upstream, our fork diff got reduced by ~33%.

Update reth fork

---

.github/workflows/integration-tests.yml
.github/workflows/run-benchmark.yml
Cargo.lock
Cargo.toml
ere-guests/Cargo.toml
precompile-patches/zisk.toml
tests/src/stateless_validator.rs

This PR updates `ere` to the latest commit, which:
- Enables to fix #173
- Update ZisK related configurations (i.e, precompiles, deps)

Update ere, enable Pico proving in integration tests & ZisK v0.12.0 adjustments
